# Docker Hub Secret for Kubernetes
# This secret should be created manually using kubectl:
#
# kubectl create secret docker-registry dockerhub-secret \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=jehanzaib08 \
#   --docker-password=<YOUR_DOCKERHUB_PASSWORD> \
#   --docker-email=<YOUR_EMAIL> \
#   --namespace=idurar-crm
#
# Or create it via Jenkins pipeline using:
# kubectl create secret docker-registry dockerhub-secret \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=${DOCKERHUB_USERNAME} \
#   --docker-password=${DOCKERHUB_CREDENTIALS_PSW} \
#   --namespace=idurar-crm \
#   --dry-run=client -o yaml | kubectl apply -f -
